/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadastroB: typeof import('./components/register-steps/cadastroB.vue')['default']
    CadastroBasico: typeof import('./components/cadastros/cadastroBasico.vue')['default']
    CadastroPlanos: typeof import('./components/cadastros/cadastroPlanos.vue')['default']
    CadastroSaude: typeof import('./components/cadastros/CadastroSaude.vue')['default']
    CadastroSaude02: typeof import('./components/cadastros/cadastroSaude02.vue')['default']
    Form: typeof import('./components/artigos/FormArtigo.vue')['default']
    FormArtigo: typeof import('./components/artigos/FormArtigo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBars: typeof import('./components/navigation/ToolBars.vue')['default']
  }
}
