/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadastroB: typeof import('./components/register-steps/cadastroB.vue')['default']
    FormArtigo: typeof import('./components/artigos/FormArtigo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MedicoForm: typeof import('./components/MedicoForm.vue')['default']
    PacienteForm: typeof import('./components/PacienteForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
