/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/adicionarConsulta/': RouteRecordInfo<'/adicionarConsulta/', '/adicionarConsulta', Record<never, never>, Record<never, never>>,
    '/agendaMedica/': RouteRecordInfo<'/agendaMedica/', '/agendaMedica', Record<never, never>, Record<never, never>>,
    '/agendaMedica/consultasPendentes/': RouteRecordInfo<'/agendaMedica/consultasPendentes/', '/agendaMedica/consultasPendentes', Record<never, never>, Record<never, never>>,
    '/analises/': RouteRecordInfo<'/analises/', '/analises', Record<never, never>, Record<never, never>>,
    '/artigos/': RouteRecordInfo<'/artigos/', '/artigos', Record<never, never>, Record<never, never>>,
    '/artigos/form': RouteRecordInfo<'/artigos/form', '/artigos/form', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/consultas/': RouteRecordInfo<'/Atleta-Screens/consultas/', '/Atleta-Screens/consultas', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/editarPerfilAtleta/': RouteRecordInfo<'/Atleta-Screens/editarPerfilAtleta/', '/Atleta-Screens/editarPerfilAtleta', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/medicoDetalhes/': RouteRecordInfo<'/Atleta-Screens/medicoDetalhes/', '/Atleta-Screens/medicoDetalhes', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/medicos/': RouteRecordInfo<'/Atleta-Screens/medicos/', '/Atleta-Screens/medicos', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/meuPlano/': RouteRecordInfo<'/Atleta-Screens/meuPlano/', '/Atleta-Screens/meuPlano', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/meusMedicos/': RouteRecordInfo<'/Atleta-Screens/meusMedicos/', '/Atleta-Screens/meusMedicos', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/perfilAtleta/': RouteRecordInfo<'/Atleta-Screens/perfilAtleta/', '/Atleta-Screens/perfilAtleta', Record<never, never>, Record<never, never>>,
    '/Atleta-Screens/visaoGeral/': RouteRecordInfo<'/Atleta-Screens/visaoGeral/', '/Atleta-Screens/visaoGeral', Record<never, never>, Record<never, never>>,
    '/certificados/': RouteRecordInfo<'/certificados/', '/certificados', Record<never, never>, Record<never, never>>,
    '/detalhesExclusaoConta': RouteRecordInfo<'/detalhesExclusaoConta', '/detalhesExclusaoConta', Record<never, never>, Record<never, never>>,
    '/esqueceuSenha/[token]': RouteRecordInfo<'/esqueceuSenha/[token]', '/esqueceuSenha/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/consultas/': RouteRecordInfo<'/Medico-Screens/consultas/', '/Medico-Screens/consultas', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/cupons/': RouteRecordInfo<'/Medico-Screens/cupons/', '/Medico-Screens/cupons', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/detalhesPaciente/': RouteRecordInfo<'/Medico-Screens/detalhesPaciente/', '/Medico-Screens/detalhesPaciente', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/editarPerfilMedico/': RouteRecordInfo<'/Medico-Screens/editarPerfilMedico/', '/Medico-Screens/editarPerfilMedico', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/editarPerfilPublico/': RouteRecordInfo<'/Medico-Screens/editarPerfilPublico/', '/Medico-Screens/editarPerfilPublico', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/pacientes/': RouteRecordInfo<'/Medico-Screens/pacientes/', '/Medico-Screens/pacientes', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/pacientesAtendidos/': RouteRecordInfo<'/Medico-Screens/pacientesAtendidos/', '/Medico-Screens/pacientesAtendidos', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/perfil-publico/': RouteRecordInfo<'/Medico-Screens/perfil-publico/', '/Medico-Screens/perfil-publico', Record<never, never>, Record<never, never>>,
    '/Medico-Screens/perfilMedico/': RouteRecordInfo<'/Medico-Screens/perfilMedico/', '/Medico-Screens/perfilMedico', Record<never, never>, Record<never, never>>,
    '/notificacoes/': RouteRecordInfo<'/notificacoes/', '/notificacoes', Record<never, never>, Record<never, never>>,
    '/novaSenhaLogado/': RouteRecordInfo<'/novaSenhaLogado/', '/novaSenhaLogado', Record<never, never>, Record<never, never>>,
    '/pagamento/': RouteRecordInfo<'/pagamento/', '/pagamento', Record<never, never>, Record<never, never>>,
    '/politicaPrivacidade': RouteRecordInfo<'/politicaPrivacidade', '/politicaPrivacidade', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/register-medico': RouteRecordInfo<'/register-medico', '/register-medico', Record<never, never>, Record<never, never>>,
    '/registerPlanos': RouteRecordInfo<'/registerPlanos', '/registerPlanos', Record<never, never>, Record<never, never>>,
    '/resumo/': RouteRecordInfo<'/resumo/', '/resumo', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/deleteAccount': RouteRecordInfo<'/settings/deleteAccount', '/settings/deleteAccount', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/validarCertificado/': RouteRecordInfo<'/validarCertificado/', '/validarCertificado', Record<never, never>, Record<never, never>>,
  }
}
